import { Nunito } from 'next/font/google';

import AuthProvider from '@/providers/AuthProvider';
import ToasterProvider from '@/providers/ToasterProvider';

import Layout from '@/components/Layout';
import './globals.css';

const nunito = Nunito({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <AuthProvider>
          <ToasterProvider />
          <Layout>
            {children}
          </Layout>
        </AuthProvider>
      </body>
    </html>
  );
};

